#!/usr/bin/env python3
"""POSIX counterpart of claude-task-monitor.sh — ClaudeTaskMonitorPosix.

The Windows monitor drives Task Scheduler through PowerShell, so it can only
ever run on Windows (`platform: windows` in the registry). That left the full
tier on Linux and macOS with no alert about a failed task AT ALL: the units are
generated by scripts/gen-scheduler.py, they fail silently, and the only way to
learn about it was `systemctl --user list-units --failed` by hand. The README
promises portability; this is the half that was missing.

What it reports, for the bundle's OWN units only (the names come from
cron/registry.yaml — a failing unit that is not ours is not our business):

  * Linux  — `systemctl --user show <task>.service`: a unit whose last run
    ended with Result != success or a non-zero exit status.
  * macOS  — `launchctl list`: a `com.claude-bundle.<task>` agent whose last
    exit status is non-zero.
  * Linux  — a unit still ACTIVE past its own `timeout_hours`. Same reasoning
    as the Windows monitor: a task that hangs holds its instance, every later
    trigger is dropped, and "still running" reads as healthy. launchd exposes no
    start time in `launchctl list`, so that half of the check is Linux-only.

Alerts go to Telegram in the same format as the Windows monitor, and every run
writes one terminal record to the ledger (cron/runs.py), so bundle-status can
tell "the POSIX monitor ran and found nothing" from "it never reported".

Exit code semantics, also copied from the Windows monitor: reporting somebody
else's failed unit is a SUCCESSFUL monitor run (0). Failing to measure, or
failing to deliver the alert, is the monitor's own failure (1).

Schedule: daily (see cron/registry.yaml). Ships disabled — enable it on a POSIX
box once the units are installed.
"""

# Declared I/O for scripts/check-io-matrix.py, which fails when this line and
# the table in docs/cron-architecture.md disagree. The code is the source; the
# doc reflects it. Keep it honest — it is what people read to decide whether to
# enable this task.
# bundle-io: offbox=a failure summary naming the bundle's own units -> Telegram Bot API money=no writes=cron/state/task-monitor-posix-seen.json
from __future__ import annotations

import json
import os
import socket
import subprocess
import sys
from datetime import datetime, timedelta
from pathlib import Path

BUNDLE_ROOT = Path(__file__).resolve().parents[1]
CRON_DIR = BUNDLE_ROOT / "cron"
LOG_DIR = CRON_DIR / "logs"
STATE_PATH = CRON_DIR / "state" / "task-monitor-posix-seen.json"
REGISTRY = CRON_DIR / "registry.yaml"
TELEGRAM_SH = CRON_DIR / "telegram-send.sh"

sys.path.insert(0, str(CRON_DIR / "hooks"))
from utils import find_bash  # noqa: E402

sys.path.insert(0, str(CRON_DIR))
from runs import terminal_record  # noqa: E402

DATE = datetime.now().strftime("%Y-%m-%d")
LOG_FILE = LOG_DIR / f"task-monitor-posix_{DATE}.log"
LAUNCHD_PREFIX = "com.claude-bundle."


def log(msg: str) -> None:
    """Print AND append to the day's log — best effort.

    An unreadable log directory must not take the monitor down before it has
    written its ledger record; that is the failure terminal_record() exists for.
    """
    line = f"[{datetime.now().strftime('%H:%M:%S')}] {msg}"
    print(line, flush=True)
    try:
        LOG_DIR.mkdir(parents=True, exist_ok=True)
        with LOG_FILE.open("a", encoding="utf-8") as fh:
            fh.write(line + "\n")
    except OSError as exc:
        print(f"  (log not written: {exc})", file=sys.stderr)


def registry_tasks() -> list[dict]:
    """Enabled registry tasks that can run on this box.

    PyYAML when available, else a small line parser — the same dual loader the
    guard scripts use, so a machine without PyYAML still gets a monitor rather
    than a traceback.
    """
    try:
        text = REGISTRY.read_text(encoding="utf-8")
    except OSError as exc:
        log(f"registry unreadable ({exc}) — nothing to check")
        return []
    tasks: list[dict] = []
    try:
        import yaml
        tasks = [t for t in (yaml.safe_load(text).get("tasks") or [])
                 if isinstance(t, dict)]
    except Exception:
        cur: dict | None = None
        for raw in text.splitlines():
            stripped = raw.strip()
            if stripped.startswith("- name:"):
                cur = {"name": stripped.split(":", 1)[1].strip().strip("'\"")}
                tasks.append(cur)
            elif cur is not None and stripped.startswith("enabled:"):
                cur["enabled"] = stripped.split(":", 1)[1].strip() != "false"
            elif cur is not None and stripped.startswith("platform:"):
                cur["platform"] = stripped.split(":", 1)[1].strip()
            elif cur is not None and stripped.startswith("timeout_hours:"):
                val = stripped.split(":", 1)[1].strip()
                cur["timeout_hours"] = int(val) if val.isdigit() else None
            elif cur is not None and stripped.startswith("health_port:"):
                # Without this line the port probe would simply not run on a box
                # that has no PyYAML — a check that is silently absent is worse
                # than one that is missing loudly.
                val = stripped.split(":", 1)[1].strip()
                cur["health_port"] = int(val) if val.isdigit() else None
            elif cur is not None and stripped.startswith("trigger:"):
                cur["trigger"] = stripped.split(":", 1)[1].strip().strip("'\"")
    out = []
    for t in tasks:
        if not t.get("name") or t.get("enabled") is False:
            continue
        if str(t.get("platform", "all")).lower() == "windows":
            continue
        out.append(t)
    return out


def _run(argv: list[str], timeout: int = 60) -> tuple[int, str]:
    """(rc, stdout+stderr) for a probe command. A missing binary is rc 127."""
    try:
        r = subprocess.run(argv, capture_output=True, timeout=timeout, check=False)
    except (OSError, subprocess.SubprocessError) as exc:
        return 127, f"{type(exc).__name__}: {exc}"
    return r.returncode, (r.stdout + r.stderr).decode("utf-8", errors="replace")


def _systemd_props(text: str) -> dict[str, str]:
    props = {}
    for line in text.splitlines():
        if "=" in line:
            k, v = line.split("=", 1)
            props[k.strip()] = v.strip()
    return props


def _systemd_timestamp(value: str) -> datetime | None:
    """`ExecMainStartTimestamp` → datetime, or None.

    systemd prints `Tue 2026-09-08 02:30:01 CEST`; the weekday and the zone name
    are dropped rather than parsed — a hung-for-hours judgement does not need
    sub-hour precision, and %Z is not portable for arbitrary zone names.
    """
    parts = value.split()
    for i, tok in enumerate(parts):
        if len(tok) == 10 and tok[4] == "-" and tok[7] == "-":
            try:
                return datetime.strptime(" ".join(parts[i:i + 2]), "%Y-%m-%d %H:%M:%S")
            except (ValueError, IndexError):
                return None
    return None


def check_systemd(tasks: list[dict]) -> tuple[list[tuple[str, str]], str | None]:
    """[(task, line)] for failed or hung units. Second value = a collection error."""
    rc, _ = _run(["systemctl", "--user", "--version"])
    if rc != 0:
        return [], "systemctl --user is not available on this host"
    problems: list[tuple[str, str]] = []
    now = datetime.now()
    for task in tasks:
        name = task["name"]
        rc, out = _run(["systemctl", "--user", "show", f"{name}.service",
                        "-p", "LoadState", "-p", "ActiveState", "-p", "Result",
                        "-p", "ExecMainStatus", "-p", "ExecMainStartTimestamp",
                        "-p", "InactiveEnterTimestamp"])
        if rc != 0:
            continue
        p = _systemd_props(out)
        if p.get("LoadState") in (None, "not-found", "masked"):
            # The unit was never installed here. That is a deployment choice, not
            # a failure — the same silence the Windows monitor keeps about a task
            # that is not registered.
            continue
        status = p.get("ExecMainStatus", "0")
        result = p.get("Result", "success")
        if result not in ("success", "") or (status.isdigit() and int(status) != 0):
            when = p.get("InactiveEnterTimestamp") or "unknown"
            problems.append((name, f"{name}: exit {status} (result={result}, "
                                   f"last run: {when})"))
            continue
        hours = task.get("timeout_hours")
        started = _systemd_timestamp(p.get("ExecMainStartTimestamp", ""))
        if (p.get("ActiveState") in ("active", "activating") and started
                and isinstance(hours, int) and hours > 0
                and now - started > timedelta(hours=hours)):
            problems.append((name, f"{name}: running since "
                                   f"{started:%Y-%m-%d %H:%M}, past its "
                                   f"timeout_hours={hours} — the unit should "
                                   f"have been killed (RuntimeMaxSec)"))
    return problems, None


def check_health_ports(tasks: list[dict]) -> list[tuple[str, str]]:
    """[(task, line)] for declared services whose port is not listening.

    The one task shape where the scheduler's own answer is worthless. A unit (or
    a Windows task) triggered at boot counts as "running" for as long as the
    process exists, and its last exit status stays 0 — so a daemon that started,
    crashed and never came back reads as healthy indefinitely, and every
    freshness rule the monitor has (built to stop it crying about old runs)
    hides it further. Upstream the first run of this probe found an MCP server
    that had been refusing connections for over a day while the monitor happily
    reported nothing.

    Only tasks that declare `health_port` are probed; loopback only, because the
    question is whether THIS machine's service is up, and a short timeout,
    because a monitor must not hang on a wedged socket.
    """
    problems: list[tuple[str, str]] = []
    for task in tasks:
        port = task.get("health_port")
        if not isinstance(port, int) or not 1 <= port <= 65535:
            continue
        try:
            with socket.create_connection(("127.0.0.1", port), timeout=3):
                continue
        except OSError as exc:
            problems.append((task["name"],
                             f"{task['name']}: nothing listening on port {port} "
                             f"({type(exc).__name__}) — the {task.get('trigger', '?')} "
                             f"service is down, whatever its exit status says"))
    return problems


def check_launchd(tasks: list[dict]) -> tuple[list[tuple[str, str]], str | None]:
    """[(task, line)] for agents whose last exit status is non-zero.

    `launchctl list` prints PID, last exit status and label. It carries no start
    time, so the "hung past timeout_hours" half of the Linux check has no macOS
    equivalent here — that is a known gap, not an oversight.
    """
    rc, out = _run(["launchctl", "list"])
    if rc != 0:
        return [], "launchctl list failed on this host"
    wanted = {t["name"] for t in tasks}
    problems: list[tuple[str, str]] = []
    for line in out.splitlines()[1:]:
        cols = line.split()
        if len(cols) < 3 or not cols[2].startswith(LAUNCHD_PREFIX):
            continue
        name = cols[2][len(LAUNCHD_PREFIX):]
        if name not in wanted:
            continue
        status = cols[1]
        if status.lstrip("-").isdigit() and int(status) != 0:
            problems.append((name, f"{name}: exit {status} (launchd agent "
                                   f"{cols[2]})"))
    return problems, None


def load_seen() -> dict:
    try:
        seen = json.loads(STATE_PATH.read_text(encoding="utf-8"))
        return seen if isinstance(seen, dict) else {}
    except (OSError, ValueError):
        return {}


def save_seen(seen: dict) -> None:
    try:
        STATE_PATH.parent.mkdir(parents=True, exist_ok=True)
        STATE_PATH.write_text(json.dumps(seen, indent=1), encoding="utf-8")
    except OSError as exc:
        log(f"state not written ({exc}) — the next run may repeat this alert")


def send_telegram(text: str) -> bool:
    """True when the alert was delivered. A monitor that cannot deliver failed."""
    bash = find_bash()
    if not bash or not TELEGRAM_SH.is_file():
        log("telegram-send.sh or bash not available — alert NOT delivered")
        return False
    try:
        r = subprocess.run([bash, str(TELEGRAM_SH), text], timeout=120, check=False)
    except (OSError, subprocess.TimeoutExpired) as exc:
        log(f"telegram: not sent ({exc})")
        return False
    return r.returncode == 0


def main() -> int:
    if os.name == "nt":
        # The Windows counterpart is claude-task-monitor.sh, which reads Task
        # Scheduler itself. Running both would double every alert.
        log("this is the POSIX monitor — on Windows use claude-task-monitor.sh")
        return 0

    with terminal_record("ClaudeTaskMonitorPosix", delivery="n/a") as rec:
        rec["artifact_path"] = LOG_FILE
        log(f"=== POSIX task monitor {DATE} ===")
        tasks = registry_tasks()
        log(f"{len(tasks)} enabled task(s) in the registry apply to this platform")

        if sys.platform == "darwin":
            problems, collect_error = check_launchd(tasks)
        else:
            problems, collect_error = check_systemd(tasks)
        # Port probes run regardless of the init system: a declared service is
        # either answering or it is not, and that question outranks whatever the
        # scheduler believes about the task.
        problems = problems + check_health_ports(tasks)

        rec["useful_items"] = len(tasks)
        if collect_error:
            # Failing to MEASURE is the monitor's own failure — "monitor down,
            # nobody noticed" is exactly what it exists to prevent.
            log(f"collection FAILED: {collect_error}")
            msg = (f"Bundle task monitor (POSIX): status collection FAILED — "
                   f"{collect_error}. Nothing was verified this run.")
            delivered = send_telegram(msg)
            rec["delivery"] = "ok" if delivered else "failed"
            rec["process_rc"] = 1
            rec["note"] = f"collection failed: {collect_error}"[:300]
            return 1

        # Only alert on a (task, line) pair that has not been alerted about
        # before — the Windows monitor's rule, for the same reason: an unfixed
        # failure that reports every morning stops being read.
        seen = load_seen()
        fresh = [(name, line) for name, line in problems if seen.get(name) != line]
        for name, line in problems:
            log(line if seen.get(name) != line else f"{line} (already reported)")
            seen[name] = line
        for name in list(seen):
            if name not in {n for n, _ in problems}:
                seen.pop(name, None)
        save_seen(seen)

        if not fresh:
            log("no new failures")
            rec["note"] = f"{len(tasks)} task(s) checked, {len(problems)} failing"
            return 0

        body = "\n".join(line for _, line in fresh)
        msg = (f"Bundle tasks (POSIX): {len(fresh)} failed unit(s)\n\n{body}\n\n"
               f"Check logs: cron/logs/\n")
        delivered = send_telegram(msg)
        rec["delivery"] = "ok" if delivered else "failed"
        rec["note"] = f"{len(tasks)} task(s) checked, {len(fresh)} new failure(s)"
        if not delivered:
            log("ALERT DELIVERY FAILED — the alert was NOT delivered")
            rec["process_rc"] = 1
            return 1
        log(f"alert sent ({len(fresh)} new failure(s))")
        return 0


if __name__ == "__main__":
    sys.exit(main())
