#!/usr/bin/env python3
"""POSIX counterpart of claude-task-monitor.sh — ClaudeTaskMonitorPosix.

The Windows monitor drives Task Scheduler through PowerShell, so it can only
ever run on Windows (`platform: windows` in the registry). That left the full
tier on Linux and macOS with no alert about a failed task AT ALL: the units are
generated by scripts/gen-scheduler.py, they fail silently, and the only way to
learn about it was `systemctl --user list-units --failed` by hand. The README
promises portability; this is the half that was missing.

What it reports, for the bundle's OWN units only (the names come from
cron/registry.yaml — a failing unit that is not ours is not our business):

  * Linux  — `systemctl --user show <task>.service`: a unit whose last run
    ended with Result != success or a non-zero exit status.
  * macOS  — `launchctl list`: a `com.claude-bundle.<task>` agent whose last
    exit status is non-zero.
  * Linux  — a unit still ACTIVE past its own `timeout_hours`. Same reasoning
    as the Windows monitor: a task that hangs holds its instance, every later
    trigger is dropped, and "still running" reads as healthy. launchd exposes no
    start time in `launchctl list`, so that half of the check is Linux-only.
  * Both   — a task gone silent in the run ledger (cron/runs.py): enabled with a
    time trigger, and no record within its window. A unit that stopped firing
    has no failed run for systemd or launchd to show. Each silence is reported
    once and repeated in the Monday digest — the Windows monitor's StaleVerdict
    check, through the same function.

Alerts go to Telegram in the same format as the Windows monitor, and every run
writes one terminal record to the ledger (cron/runs.py), so bundle-status can
tell "the POSIX monitor ran and found nothing" from "it never reported".

Exit code semantics, also copied from the Windows monitor: reporting somebody
else's failed unit is a SUCCESSFUL monitor run (0). Failing to measure, or
failing to deliver the alert, is the monitor's own failure (1).

Schedule: daily (see cron/registry.yaml). Ships disabled — enable it on a POSIX
box once the units are installed.
"""

# Declared I/O for scripts/check-io-matrix.py, which fails when this line and
# the table in docs/cron-architecture.md disagree. The code is the source; the
# doc reflects it. Keep it honest — it is what people read to decide whether to
# enable this task.
# bundle-io: offbox=a failure summary naming the bundle's own units (failed ones, and tasks gone silent in the run ledger) and a down LLM chain's providers -> Telegram Bot API money=no writes=cron/state/task-monitor-posix-seen.json
from __future__ import annotations

import json
import os
import subprocess
import sys
from datetime import datetime, timedelta
from pathlib import Path

BUNDLE_ROOT = Path(__file__).resolve().parents[1]
CRON_DIR = BUNDLE_ROOT / "cron"
LOG_DIR = CRON_DIR / "logs"
STATE_PATH = CRON_DIR / "state" / "task-monitor-posix-seen.json"
CHAIN_DEAD_PATH = CRON_DIR / "state" / "chain-dead.json"
REGISTRY = CRON_DIR / "registry.yaml"
TELEGRAM_SH = CRON_DIR / "telegram-send.sh"

sys.path.insert(0, str(CRON_DIR / "hooks"))
from utils import find_bash  # noqa: E402

sys.path.insert(0, str(CRON_DIR))
from runs import STALE_SEEN_KEY, stale_alert, terminal_record  # noqa: E402
# Shared with the Windows monitor (claude-task-monitor.sh): the registry parser,
# the service port probe and the once-per-outage LLM-chain report. Two copies
# had already drifted — see monitor_checks' header.
from monitor_checks import (  # noqa: E402
    CHAIN_SEEN_KEY, chain_dead_report, check_health_ports, read_registry)

DATE = datetime.now().strftime("%Y-%m-%d")
LOG_FILE = LOG_DIR / f"task-monitor-posix_{DATE}.log"
LAUNCHD_PREFIX = "com.claude-bundle."


def log(msg: str) -> None:
    """Print AND append to the day's log — best effort.

    An unreadable log directory must not take the monitor down before it has
    written its ledger record; that is the failure terminal_record() exists for.
    """
    line = f"[{datetime.now().strftime('%H:%M:%S')}] {msg}"
    print(line, flush=True)
    try:
        LOG_DIR.mkdir(parents=True, exist_ok=True)
        with LOG_FILE.open("a", encoding="utf-8") as fh:
            fh.write(line + "\n")
    except OSError as exc:
        print(f"  (log not written: {exc})", file=sys.stderr)


def registry_tasks() -> list[dict]:
    """Enabled registry tasks that can run on this box.

    Parsed by monitor_checks.read_registry: PyYAML when available, else a line
    parser that knows every field a monitor reads, so a machine without PyYAML
    still gets a monitor — and the same checks — rather than a traceback.
    """
    try:
        tasks = read_registry(REGISTRY)
    except OSError as exc:
        log(f"registry unreadable ({exc}) — nothing to check")
        return []
    out = []
    for t in tasks:
        if not t.get("name") or t.get("enabled") is False:
            continue
        if str(t.get("platform", "all")).lower() == "windows":
            continue
        out.append(t)
    return out


def _run(argv: list[str], timeout: int = 60) -> tuple[int, str]:
    """(rc, stdout+stderr) for a probe command. A missing binary is rc 127."""
    try:
        r = subprocess.run(argv, capture_output=True, timeout=timeout, check=False)
    except (OSError, subprocess.SubprocessError) as exc:
        return 127, f"{type(exc).__name__}: {exc}"
    return r.returncode, (r.stdout + r.stderr).decode("utf-8", errors="replace")


def _systemd_props(text: str) -> dict[str, str]:
    props = {}
    for line in text.splitlines():
        if "=" in line:
            k, v = line.split("=", 1)
            props[k.strip()] = v.strip()
    return props


def _systemd_timestamp(value: str) -> datetime | None:
    """`ExecMainStartTimestamp` → datetime, or None.

    systemd prints `Tue 2026-09-08 02:30:01 CEST`; the weekday and the zone name
    are dropped rather than parsed — a hung-for-hours judgement does not need
    sub-hour precision, and %Z is not portable for arbitrary zone names.
    """
    parts = value.split()
    for i, tok in enumerate(parts):
        if len(tok) == 10 and tok[4] == "-" and tok[7] == "-":
            try:
                return datetime.strptime(" ".join(parts[i:i + 2]), "%Y-%m-%d %H:%M:%S")
            except (ValueError, IndexError):
                return None
    return None


def check_systemd(tasks: list[dict]) -> tuple[list[tuple[str, str]], str | None]:
    """[(task, line)] for failed or hung units. Second value = a collection error."""
    rc, _ = _run(["systemctl", "--user", "--version"])
    if rc != 0:
        return [], "systemctl --user is not available on this host"
    problems: list[tuple[str, str]] = []
    now = datetime.now()
    for task in tasks:
        name = task["name"]
        rc, out = _run(["systemctl", "--user", "show", f"{name}.service",
                        "-p", "LoadState", "-p", "ActiveState", "-p", "Result",
                        "-p", "ExecMainStatus", "-p", "ExecMainStartTimestamp",
                        "-p", "InactiveEnterTimestamp"])
        if rc != 0:
            continue
        p = _systemd_props(out)
        if p.get("LoadState") in (None, "not-found", "masked"):
            # The unit was never installed here. That is a deployment choice, not
            # a failure — the same silence the Windows monitor keeps about a task
            # that is not registered.
            continue
        status = p.get("ExecMainStatus", "0")
        result = p.get("Result", "success")
        if result not in ("success", "") or (status.isdigit() and int(status) != 0):
            when = p.get("InactiveEnterTimestamp") or "unknown"
            problems.append((name, f"{name}: exit {status} (result={result}, "
                                   f"last run: {when})"))
            continue
        hours = task.get("timeout_hours")
        started = _systemd_timestamp(p.get("ExecMainStartTimestamp", ""))
        if (p.get("ActiveState") in ("active", "activating") and started
                and isinstance(hours, int) and hours > 0
                and now - started > timedelta(hours=hours)):
            problems.append((name, f"{name}: running since "
                                   f"{started:%Y-%m-%d %H:%M}, past its "
                                   f"timeout_hours={hours} — the unit should "
                                   f"have been killed (RuntimeMaxSec)"))
    return problems, None


def check_launchd(tasks: list[dict]) -> tuple[list[tuple[str, str]], str | None]:
    """[(task, line)] for agents whose last exit status is non-zero.

    `launchctl list` prints PID, last exit status and label. It carries no start
    time, so the "hung past timeout_hours" half of the Linux check has no macOS
    equivalent here — that is a known gap, not an oversight.
    """
    rc, out = _run(["launchctl", "list"])
    if rc != 0:
        return [], "launchctl list failed on this host"
    wanted = {t["name"] for t in tasks}
    problems: list[tuple[str, str]] = []
    for line in out.splitlines()[1:]:
        cols = line.split()
        if len(cols) < 3 or not cols[2].startswith(LAUNCHD_PREFIX):
            continue
        name = cols[2][len(LAUNCHD_PREFIX):]
        if name not in wanted:
            continue
        status = cols[1]
        if status.lstrip("-").isdigit() and int(status) != 0:
            problems.append((name, f"{name}: exit {status} (launchd agent "
                                   f"{cols[2]})"))
    return problems, None


def load_seen() -> dict:
    try:
        seen = json.loads(STATE_PATH.read_text(encoding="utf-8"))
        return seen if isinstance(seen, dict) else {}
    except (OSError, ValueError):
        return {}


def save_seen(seen: dict) -> None:
    try:
        STATE_PATH.parent.mkdir(parents=True, exist_ok=True)
        STATE_PATH.write_text(json.dumps(seen, indent=1), encoding="utf-8")
    except OSError as exc:
        log(f"state not written ({exc}) — the next run may repeat this alert")


def send_telegram(text: str) -> bool:
    """True when the alert was delivered. A monitor that cannot deliver failed."""
    bash = find_bash()
    if not bash or not TELEGRAM_SH.is_file():
        log("telegram-send.sh or bash not available — alert NOT delivered")
        return False
    try:
        r = subprocess.run([bash, str(TELEGRAM_SH), text], timeout=120, check=False)
    except (OSError, subprocess.TimeoutExpired) as exc:
        log(f"telegram: not sent ({exc})")
        return False
    return r.returncode == 0


def main() -> int:
    if os.name == "nt":
        # The Windows counterpart is claude-task-monitor.sh, which reads Task
        # Scheduler itself. Running both would double every alert.
        log("this is the POSIX monitor — on Windows use claude-task-monitor.sh")
        return 0

    with terminal_record("ClaudeTaskMonitorPosix", delivery="n/a") as rec:
        rec["artifact_path"] = LOG_FILE
        log(f"=== POSIX task monitor {DATE} ===")
        tasks = registry_tasks()
        log(f"{len(tasks)} enabled task(s) in the registry apply to this platform")

        if sys.platform == "darwin":
            problems, collect_error = check_launchd(tasks)
        else:
            problems, collect_error = check_systemd(tasks)
        # Port probes run regardless of the init system: a declared service is
        # either answering or it is not, and that question outranks whatever the
        # scheduler believes about the task.
        problems = problems + check_health_ports(tasks)

        rec["useful_items"] = len(tasks)
        if collect_error:
            # Failing to MEASURE is the monitor's own failure — "monitor down,
            # nobody noticed" is exactly what it exists to prevent.
            log(f"collection FAILED: {collect_error}")
            msg = (f"Bundle task monitor (POSIX): status collection FAILED — "
                   f"{collect_error}. Nothing was verified this run.")
            delivered = send_telegram(msg)
            rec["delivery"] = "ok" if delivered else "failed"
            rec["process_rc"] = 1
            rec["note"] = f"collection failed: {collect_error}"[:300]
            return 1

        # Only alert on a (task, line) pair that has not been alerted about
        # before — the Windows monitor's rule, for the same reason: an unfixed
        # failure that reports every morning stops being read.
        seen = load_seen()
        now = datetime.now()
        # The LLM provider chain, once per outage — the same rule and wording as
        # the Windows monitor (monitor_checks.chain_dead_report). It keeps its
        # own key in `seen`, which the prune below must leave alone.
        chain = chain_dead_report(seen, now, CHAIN_DEAD_PATH)
        if chain:
            log(chain)
        # Tasks gone silent in the run ledger. systemd and launchd only show runs
        # that happened, so a unit that stopped firing has nothing to fail above —
        # it was the one failure this monitor could not report at all. The Windows
        # monitor's StaleVerdict check, through the same function
        # (runs.stale_alert): once per (task, bucket), a Monday digest for the rest.
        try:
            stale, standing = stale_alert(seen, now, registry=REGISTRY)
            stale_block = (["StaleVerdict: task(s) have not reported a run in a while",
                            *stale] if stale else [])
        except Exception as exc:
            # As on Windows (rc > 1 there): for the check whose job is noticing
            # silence, a crash must not read as a clean bill of health.
            standing = []
            stale_block = [f"StaleVerdict: the staleness check itself failed "
                           f"({type(exc).__name__}: {exc}) — nothing was verified"]
        for line in stale_block:
            log(line)
        if standing:
            log(f"already reported, still stale: {', '.join(standing)}")
        fresh = [(name, line) for name, line in problems if seen.get(name) != line]
        for name, line in problems:
            log(line if seen.get(name) != line else f"{line} (already reported)")
            seen[name] = line
        for name in list(seen):
            if (name not in (CHAIN_SEEN_KEY, STALE_SEEN_KEY)
                    and name not in {n for n, _ in problems}):
                seen.pop(name, None)
        save_seen(seen)

        if not fresh and not chain and not stale_block:
            log("no new failures")
            rec["note"] = f"{len(tasks)} task(s) checked, {len(problems)} failing"
            return 0

        body = "\n".join(([chain] if chain else []) + [line for _, line in fresh]
                         + stale_block)
        header = (f"Bundle tasks (POSIX): {len(fresh)} failed unit(s)" if fresh
                  else "Bundle tasks (POSIX): attention needed")
        msg = f"{header}\n\n{body}\n\nCheck logs: cron/logs/\n"
        delivered = send_telegram(msg)
        rec["delivery"] = "ok" if delivered else "failed"
        rec["note"] = f"{len(tasks)} task(s) checked, {len(fresh)} new failure(s)"
        if not delivered:
            log("ALERT DELIVERY FAILED — the alert was NOT delivered")
            rec["process_rc"] = 1
            return 1
        log(f"alert sent ({len(fresh)} new failure(s))")
        return 0


if __name__ == "__main__":
    sys.exit(main())
