"""Every variable name config/llm-providers.example.env carries. GENERATED.

Do not edit: `python scripts/check-env-ref.py --emit-names` rewrites this file
from the template, and `python scripts/check-env-ref.py` (CI) fails while the
two disagree. It exists because config/ is not deployed, so code running from
an installed cron/ cannot read the template itself.
"""

TEMPLATE_NAMES = frozenset({
    "AGENTS_SYNC_FIX_MODEL",
    "ANTHROPIC_API_KEY",
    "API_TIMEOUT_MS",
    "BASH_EXE",
    "CCR_API_KEY",
    "CCR_HOST",
    "CLAUDE_BIN",
    "CLAUDE_STOP_ALERT_COOLDOWN_MINUTES",
    "CLAUDE_STOP_ALERT_MINUTES",
    "DEEPINFRA_BASE_URL",
    "DEEPINFRA_KEY",
    "DEEPINFRA_MODEL",
    "DEEPSEEK_BASE_URL",
    "DEEPSEEK_KEY",
    "DEEPSEEK_MODEL",
    "GIT_NET_TIMEOUT",
    "HANDOFF_WAIT_SECONDS",
    "HEALTHCHECK_DISK_EXCLUDE",
    "HEALTHCHECK_DISK_PCT",
    "HEALTHCHECK_REMOTE_DISK_PCT",
    "KB_SOURCE_DIR",
    "LOCAL_LLM_ALLOWED_HOSTS",
    "LOCAL_LLM_BASE_URL",
    "LOCAL_LLM_KEY",
    "LOCAL_LLM_MODEL",
    "MD2PDF_BROWSER",
    "MD2PDF_TIMEOUT",
    "MEMORY_CROSS_NOTES",
    "MINIMAX_API_KEY",
    "MONITOR_EXCLUDE_TASKS",
    "OLLAMA_HOST",
    "OPENCODE_GO_API_KEY",
    "OPENCODE_GO_MODEL",
    "PROJECTS_ROOT",
    "PYTHON_EXE",
    "REMOTE_SSH_HOST",
    "SESSION_START_MAX_CHARS",
    "SYNC_CHECK_PRIVATE_HOSTS",
    "TELEGRAM_BOT_TOKEN",
    "TELEGRAM_CHAT_ID",
    "TEST_SWEEP_RUN_BUDGET",
    "TEST_SWEEP_SKIP",
    "TEST_SWEEP_TELEGRAM",
    "TEST_SWEEP_TIMEOUT",
    "TEST_SWEEP_TIMEOUT_FULL",
    "WAIT_FOR_PATTERN",
    "WARM_MODEL",
    "WIKI_ALLOW_OFFBOX",
    "WIKI_BACKLOG_MAX",
    "WIKI_HANDOFF_RETENTION_DAYS",
    "WIKI_LINT_TELEGRAM",
    "WIKI_LLM_LOCK_STALE",
    "WIKI_LLM_LOCK_WAIT",
    "WIKI_LLM_PACE_SECONDS",
    "WIKI_LLM_PROVIDER",
    "WIKI_LOG_RETENTION_DAYS",
    "WIKI_MASK_SECRETS",
    "WIKI_OFFBOX_FALLBACK",
    "WIKI_PROJECT_LOG_MAX_LINES",
    "WIKI_REJECTED_RETENTION_DAYS",
    "WIKI_RETRY_LIMIT",
    "WIN_REMOTE_HOST",
})
